label: Překlad
tips:
  locale-language:
    label: 'Jazyk překladu'
  locale-translate:
    label: Přeložit
  locale-validate:
    label: 'Validovat překlad'
  locale-continue:
    label: 'Pokračování na'
