display:
  default:
    display_options:
      fields:
        title:
          label: Název
        name:
          label: Autor
        status:
          label: Stav
      exposed_form:
        options:
          submit_button: Filtr
      filters:
        title:
          expose:
            label: Název
        status:
          expose:
            label: Stav
        langcode:
          expose:
            label: Jazyk
