display:
  default:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
        name:
          label: Autor
      exposed_form:
        options:
          submit_button: Filtr
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
        name:
          label: Autor
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
