label: Komentáře
display:
  default:
    display_title: Výchozí
    display_options:
      title: Komentáře
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
        name:
          label: Autor
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      empty:
        area_text_custom:
          content: 'Bez komentářů.'
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
  page_unapproved:
    display_title: 'Neschválené komentáře'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
        name:
          label: Autor
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
