label: 'Moderovaný obsah'
display:
  default:
    display_title: Výchozí
    display_options:
      title: 'Moderovaný obsah'
      fields:
        title:
          label: Název
        name:
          label: Autor
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        title:
          expose:
            label: Název
        langcode:
          expose:
            label: Jazyk
