display:
  default:
    display_options:
      fields:
        title:
          label: Název
        status:
          label: Stav
      arguments:
        gid:
          exception:
            title: Vše
      filters:
        type:
          expose:
            label: Typ
