_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    en-gb: en-gb
    cs: cs
  domains:
    en: ''
    en-gb: ''
    cs: ''
selected_langcode: site_default
